### ISSUE TITLE
npm test yields Error: Error watching file for changes: EMFILE

### ISSUE THREAD

**Issue by pgte** [ipfs-shipyard/peerpad#14]
```
→ npm test

> peerpad@0.1.0 test /Users/pedroteixeira/projects/ipfs/peerpad
> npm run lint && react-scripts test --env=jsdom


> peerpad@0.1.0 lint /Users/pedroteixeira/projects/ipfs/peerpad
> standard

2017-08-23 12:02 node[3967] (FSEvents.framework) FSEventStreamStart: register_with_server: ERROR: f2d_register_rpc() => (null) (-22)
2017-08-23 12:02 node[3967] (FSEvents.framework) FSEventStreamStart: register_with_server: ERROR: f2d_register_rpc() => (null) (-22)
2017-08-23 12:02 node[3967] (FSEvents.framework) FSEventStreamStart: register_with_server: ERROR: f2d_register_rpc() => (null) (-22)
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: Error watching file for changes: EMFILE
    at exports._errnoException (util.js:1018:11)
    at FSEvent.FSWatcher._handle.onchange (fs.js:1420:11)
npm ERR! Test failed.  See above for more details.
```

**Comment by pgte** [comment]
Fixed by https://github.com/facebookincubator/create-react-app/issues/871
